/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Andre-Coude
 */
public class Navios extends javax.swing.JPanel {

    /**
     * Creates new form Navios
     */
    private boolean status = true;

    public Navios() {
        initComponents();
        grupo.add(radioSubmarine);
        grupo.add(radioCruzador);
        grupo.add(radioEncouracado);
        grupo.add(radioHidro);
        grupo.add(radioPorta);


        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        radioSubmarine = new javax.swing.JRadioButton();
        radioCruzador = new javax.swing.JRadioButton();
        radioHidro = new javax.swing.JRadioButton();
        radioEncouracado = new javax.swing.JRadioButton();
        radioPorta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        porta = new javax.swing.JLabel();
        encouracado = new javax.swing.JLabel();
        hidro = new javax.swing.JLabel();
        cruzador = new javax.swing.JLabel();
        submarino = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setRequestFocusEnabled(false);

        radioSubmarine.setForeground(new java.awt.Color(51, 0, 51));
        radioSubmarine.setText("4 SUBMARINOS");
        radioSubmarine.setContentAreaFilled(false);
        radioSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSubmarineActionPerformed(evt);
            }
        });

        radioCruzador.setForeground(new java.awt.Color(51, 0, 51));
        radioCruzador.setText("3 CRUZADORES");
        radioCruzador.setContentAreaFilled(false);
        radioCruzador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCruzadorActionPerformed(evt);
            }
        });

        radioHidro.setForeground(new java.awt.Color(51, 0, 51));
        radioHidro.setSelected(true);
        radioHidro.setText("5  HIDRO-AVIÃO");
        radioHidro.setContentAreaFilled(false);
        radioHidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHidroActionPerformed(evt);
            }
        });

        radioEncouracado.setForeground(new java.awt.Color(51, 0, 51));
        radioEncouracado.setText("2 ENCOURAÇADOS");
        radioEncouracado.setContentAreaFilled(false);
        radioEncouracado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEncouracadoActionPerformed(evt);
            }
        });

        radioPorta.setForeground(new java.awt.Color(51, 0, 51));
        radioPorta.setText("1  PORTA-AVIÃO");
        radioPorta.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("COLOQUE SEU  NAVIOS EM POSIÇÃO");

        porta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/portaaviao.png"))); // NOI18N

        encouracado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/encouracado.png"))); // NOI18N

        hidro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/hidroaviao.png"))); // NOI18N

        cruzador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/cruzador.png"))); // NOI18N

        submarino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/submarino.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(porta)
                    .addComponent(encouracado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cruzador)
                            .addComponent(submarino))
                        .addGap(26, 26, 26))
                    .addComponent(hidro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioEncouracado)
                    .addComponent(radioPorta)
                    .addComponent(radioHidro)
                    .addComponent(radioCruzador)
                    .addComponent(radioSubmarine))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(porta)
                    .addComponent(radioPorta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encouracado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioEncouracado)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioHidro)
                    .addComponent(hidro))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cruzador)
                    .addComponent(radioCruzador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submarino)
                    .addComponent(radioSubmarine))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioHidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHidroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHidroActionPerformed

    private void radioSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSubmarineActionPerformed

    private void radioCruzadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCruzadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCruzadorActionPerformed

    private void radioEncouracadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEncouracadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEncouracadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cruzador;
    private javax.swing.JLabel encouracado;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel hidro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel porta;
    private javax.swing.JRadioButton radioCruzador;
    private javax.swing.JRadioButton radioEncouracado;
    private javax.swing.JRadioButton radioHidro;
    private javax.swing.JRadioButton radioPorta;
    private javax.swing.JRadioButton radioSubmarine;
    private javax.swing.JLabel submarino;
    // End of variables declaration//GEN-END:variables

    public void exibirPlayer2(boolean a) {

        encouracado.setVisible(a);
        hidro.setVisible(!a);
        cruzador.setVisible(a);
        encouracado.setVisible(a);
        submarino.setVisible(a);
        porta.setVisible(a);
        radioPorta.setVisible(a);
        radioSubmarine.setVisible(a);
        radioEncouracado.setVisible(a);
        radioCruzador.setVisible(a);
        radioHidro.setVisible(!a);

    }

    /**
     * @return the radioCruzador
     */
    public javax.swing.JRadioButton getRadioCruzador() {
        return radioCruzador;
    }

    /**
     * @return the radioEncouracado
     */
    public javax.swing.JRadioButton getRadioEncouracado() {
        return radioEncouracado;
    }

    /**
     * @return the radioHidro
     */
    public javax.swing.JRadioButton getRadioHidro() {
        return radioHidro;
    }

    /**
     * @return the radioPorta
     */
    public javax.swing.JRadioButton getRadioPorta() {
        return radioPorta;
    }

    /**
     * @return the radioSubmarine
     */
    public javax.swing.JRadioButton getRadioSubmarine() {
        return radioSubmarine;
    }

    /**
     * @return the status
     */
    public boolean isStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(boolean status) {
        this.status = status;
    }

}
