/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Andre-Coude
 */
public class PainelJogador extends javax.swing.JPanel {

    /**
     * Creates new form PainelJogador
     */
    public PainelJogador() {
        initComponents();
        lblAtaque.setVisible(false);
        vidaDois.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NOME = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vidaUm = new javax.swing.JLabel();
        vidaDois = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BATALHA NAVAL");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOME.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        NOME.setForeground(new java.awt.Color(51, 102, 255));
        NOME.setText("ANDRE CONDE");
        jPanel1.add(NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 36, 230, 22));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/capitao6.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, -1, 102));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JOGADOR :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 11, -1, -1));

        lblAtaque.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        lblAtaque.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque.setText("ATAQUE  AQUI!");
        jPanel1.add(lblAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MEU TABULEIRO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 50, -1, -1));

        vidaUm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/vida3.png"))); // NOI18N
        jPanel1.add(vidaUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, -1));

        vidaDois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/vida3.png"))); // NOI18N
        jPanel1.add(vidaDois, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOME;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel vidaDois;
    private javax.swing.JLabel vidaUm;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NOME
     */
    public javax.swing.JLabel getNOME() {
        return NOME;
    }

    /**
     * @param NOME the NOME to set
     */
    public void setNOME(javax.swing.JLabel NOME) {
        this.NOME = NOME;
    }

    /**
     * @return the lblAtaque
     */
    public javax.swing.JLabel getLblAtaque() {
        return lblAtaque;
    }

    /**
     * @return the vida
     */
    public javax.swing.JLabel getVidaUm() {
        return vidaUm;
    }

    /**
     * @return the vidaDois
     */
    public javax.swing.JLabel getVidaDois() {
        return vidaDois;
    }


}
